site_name: foodeliverty_api
site_description: The REST API for foodeliverty
repo_url: https://github.com/poyo-brands/foodeliverty
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/poyo-brands">poyo-brands</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Holidays: 'api/holidays.md'
    - Menu Categories: 'api/menu_categories.md'
    - Menu Items: 'api/menu_items.md'
    - Opening Hours: 'api/opening_hours.md'
    - Stores: 'api/stores.md'
    - Users: 'api/users.md'
