site_name: bouffet
site_description: The REST API for Bouffet
repo_url: https://github.com/poyo-brands/bouffet
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/poyo-brands">poyo-brands</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Menu Categories: 'api/menu_categories.md'
    - Menu Items: 'api/menu_items.md'
    - Opening Hours: 'api/opening_hours.md'
    - Orders: 'api/orders.md'
    - Order Items: 'api/order_items.md'
    - Stores: 'api/stores.md'
    - Users: 'api/users.md'
