# Generated by Django 3.2.10 on 2023-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
