# Generated by Django 3.2.10 on 2021-12-30 03:16

import uuid

import tenant_schemas.postgresql_backend.base
from django.db import migrations, models


def _insert_local_development_tenant(apps, _):
    Client = apps.get_model("tenants", "Client")
    tenant = Client(
        domain_url="localhost",
        schema_name="testaurant",
        name="Testaurant Inc.",
        paid_until="3000-12-31",
        on_trial=False,
    )
    tenant.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("domain_url", models.CharField(max_length=128, unique=True)),
                (
                    "schema_name",
                    models.CharField(
                        max_length=63,
                        unique=True,
                        validators=[tenant_schemas.postgresql_backend.base._check_schema_name],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("on_trial", models.BooleanField()),
                ("paid_until", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(_insert_local_development_tenant),
    ]
