# Generated by Django 3.2.10 on 2021-12-30 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
