# Generated by Django 3.2.10 on 2023-11-02 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverytrackingpoint",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_courier",
        ),
        migrations.DeleteModel(
            name="DeliveryCourier",
        ),
        migrations.DeleteModel(
            name="DeliveryTrackingPoint",
        ),
    ]
