# Generated by Django 3.2.10 on 2021-12-29 04:18

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="stores.menuitem"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="custom_labels",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_courier",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.deliverycourier"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(to="orders.OrderItem"),
        ),
        migrations.AddField(
            model_name="deliverytrackingpoint",
            name="order",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.order"),
        ),
        migrations.AddField(
            model_name="deliverycourier",
            name="custom_labels",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="custom_labels",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
